import React, { useEffect, useState, useContext } from 'react';
import axios from 'axios';
import { AdminContext } from '../../context/AdminContext';
import { motion, AnimatePresence } from 'framer-motion';
import { Loader2, Trash2, ArrowLeft, ExternalLink, AlertTriangle, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';

const AdminDocuments = () => {
    const { backendUrl } = useContext(AdminContext);
    const [documents, setDocuments] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
    const [docToDelete, setDocToDelete] = useState(null);

    const fetchDocuments = async () => {
        try {
            axios.defaults.withCredentials = true;
            const { data } = await axios.get(backendUrl + '/admin/documents');
            if (data.success) {
                setDocuments(data.documents);
            }
        } catch (error) {
            toast.error(error.message);
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        fetchDocuments();
    }, []);

    const confirmDeletePrompt = (id) => {
        setDocToDelete(id);
        setIsDeleteModalOpen(true);
    };

    const handleDeleteConfirm = async () => {
        try {
            const { data } = await axios.delete(`${backendUrl}/admin/documents/${docToDelete}`);
            if (data.success) {
                toast.success(data.message);
                setDocuments(documents.filter(doc => doc._id !== docToDelete));
                setIsDeleteModalOpen(false);
                setDocToDelete(null);
            } else {
                toast.error(data.message);
            }
        } catch (error) {
            toast.error(error.message);
        }
    };

    return (
        <div className="min-h-screen w-full bg-[#050505] p-6 font-sans text-[#F3F2ED] relative">
            <div className="flex items-center gap-4 mb-8">
                <Link to="/admin/dashboard" className="p-2 bg-[#111] border border-[#222] rounded-xl hover:border-[#1AA3A3] hover:text-[#1AA3A3] transition-colors">
                    <ArrowLeft size={20} />
                </Link>
                <div>
                    <h1 className="text-2xl font-bold text-white">Document Repository</h1>
                    <p className="text-sm text-gray-500">Monitor and manage all PDFs generated on the platform.</p>
                </div>
            </div>

            <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-[#0A0A0A] border border-[#222] rounded-2xl overflow-hidden shadow-lg"
            >
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-[#111] border-b border-[#222] text-gray-400 text-sm">
                                <th className="p-4 font-medium">Generated For (Student)</th>
                                <th className="p-4 font-medium">Generated By (Creator)</th>
                                <th className="p-4 font-medium">Original Template</th>
                                <th className="p-4 font-medium">Date</th>
                                <th className="p-4 font-medium text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {isLoading ? (
                                <tr>
                                    <td colSpan="5" className="p-8 text-center">
                                        <Loader2 className="animate-spin text-[#1AA3A3] mx-auto" size={32} />
                                    </td>
                                </tr>
                            ) : documents.length === 0 ? (
                                <tr>
                                    <td colSpan="5" className="p-8 text-center text-gray-500">
                                        No documents have been generated yet.
                                    </td>
                                </tr>
                            ) : (
                                documents.map((doc) => (
                                    <tr key={doc._id} className="border-b border-[#222] hover:bg-[#111]/50 transition-colors">
                                        {/* Who the PDF is for */}
                                        <td className="p-4">
                                            <div className="font-medium text-white">{doc.studentName}</div>
                                            <div className="text-xs text-[#F54A00] font-mono mt-1">{doc.studentPrn}</div>
                                        </td>
                                        
                                        {/* Who generated it */}
                                        <td className="p-4">
                                            <div className="text-gray-300 text-sm">{doc.userId?.name || "Unknown"}</div>
                                            <div className="text-xs text-gray-500 mt-1">{doc.userId?.email || "N/A"}</div>
                                        </td>
                                        
                                        {/* File Details */}
                                        <td className="p-4 text-gray-400 text-sm flex items-center gap-2">
                                            <FileText size={16} className="text-[#1AA3A3]" />
                                            {doc.originalName}
                                        </td>
                                        
                                        {/* Date */}
                                        <td className="p-4 text-gray-400 text-sm">
                                            {new Date(doc.createdAt).toLocaleDateString()}
                                        </td>

                                        {/* Actions */}
                                        <td className="p-4 flex items-center justify-center gap-3">
                                            <a 
                                                href={doc.pdfUrl} 
                                                target="_blank" 
                                                rel="noopener noreferrer"
                                                className="p-2 text-gray-400 hover:text-[#10B981] hover:bg-[#10B981]/10 rounded-lg transition-all"
                                                title="View PDF"
                                            >
                                                <ExternalLink size={18} />
                                            </a>
                                            <button 
                                                onClick={() => confirmDeletePrompt(doc._id)}
                                                className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-all"
                                                title="Delete Document"
                                            >
                                                <Trash2 size={18} />
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </motion.div>

            {/* Custom Delete Modal */}
            <AnimatePresence>
                {isDeleteModalOpen && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
                        <motion.div 
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 0.95 }}
                            className="bg-[#111] border border-[#333] rounded-2xl w-full max-w-sm overflow-hidden shadow-2xl p-6 text-center"
                        >
                            <div className="w-16 h-16 bg-red-500/10 text-red-500 rounded-full flex items-center justify-center mx-auto mb-5">
                                <AlertTriangle size={32} />
                            </div>
                            <h2 className="text-xl font-bold text-white mb-2">Delete Document?</h2>
                            <p className="text-gray-400 text-sm mb-8 leading-relaxed">
                                This will permanently remove the PDF record and revoke access for any users it was shared with.
                            </p>
                            <div className="flex gap-3">
                                <button 
                                    onClick={() => setIsDeleteModalOpen(false)}
                                    className="flex-1 py-3 rounded-xl border border-[#333] text-gray-300 hover:bg-[#222] transition-colors text-sm font-medium"
                                >
                                    Cancel
                                </button>
                                <button 
                                    onClick={handleDeleteConfirm}
                                    className="flex-1 py-3 rounded-xl bg-red-500 hover:bg-red-600 text-white transition-colors text-sm font-bold shadow-lg shadow-red-500/20"
                                >
                                    Yes, Delete
                                </button>
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default AdminDocuments;